### PR TITLE
Add theme color to CommandInput field when focused

### PR DESCRIPTION
**Pull request by apurv-r**
Adds the underlined color to the `CommandInput` field in `Console.tsx` to match with that of the custom theme. Minor change yea, but it adds completeness to the theme 🤷🏽‍♂️ 

Eg: 
image

(forgot to take a before changes screenshot, you could just check how it currently is)

### CODE REVIEW

**Comment by finnie2006** [comment]
Will be merged in the next version

**Comment by JohnB17** [comment]
Can you please remake this pull request to the v1.10.1 branch?

**Comment by JohnB17** [comment]
Please move this pull request to v1.10.1 branch.

**Comment by finnie2006** [comment]
This pr will not work on v1.10

**Pull request closed without merging**
