### PR TITLE
mcTheme updated

### PR DESCRIPTION
**Pull request by RTK23-dev**
change install.sh changed mc theme

### CODE REVIEW

**Comment by RTK23-dev** [comment]
just change install.sh lmao also you can change text color in main.css because black isnt 100% pog

**Review by finnie2006 — CHANGES_REQUESTED** [review]
Old one is better

**Comment by RTK23-dev** [comment]
> Old one is better

Yeah check dm

**Comment by RTK23-dev** [comment]
Better McPaste soon

**Pull request closed without merging**
