### PR TITLE
Fix spelling mistakes & grammatically incorrect words

### PR DESCRIPTION
**Pull request by WavingCatDevs**

### CODE REVIEW

**Comment by finnie2006** [comment]
The readme has indeed some spelling mistakes etc, but i will also need to fix some more stuff, for example i should not use i but we

**Comment by WavingCatDevs** [comment]
> The readme has indeed some spelling mistakes etc, but i will also need to fix some more stuff, for example i should not use i but we

Should I close this pr?

**Comment by finnie2006** [comment]
> > The readme has indeed some spelling mistakes etc, but i will also need to fix some more stuff, for example i should not use i but we
> 
> Should I close this pr then?

I mean the i and we indeed

**Comment by finnie2006** [comment]
I fixed it, thanks for pointing it to me

**Pull request closed without merging**
